# 이 파일은 JupyterHub Helm 차트의 기본 구성 값을 업데이트할 수 있습니다.
#
# 참고로 구성 참조 및 기본값을 확인하세요. 하지만 관심 있는 Helm 차트 버전을 참조하세요!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
debug:
  enabled: true

hub:
  config:
    GenericOAuthenticator:
      client_id: jupyterhub
      client_secret: jupyterhub
      oauth_callback_url: http://localhost:30002/hub/oauth_callback
      authorize_url: http://localhost:30000/realms/jhipster/protocol/openid-connect/auth
      token_url: http://keycloak:9080/realms/jhipster/protocol/openid-connect/token
      userdata_url: http://keycloak:9080/realms/jhipster/protocol/openid-connect/userinfo
      logout_redirect_url: http://localhost:30000/realms/jhipster/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:30002&client_id=jupyterhub
      login_service: keycloak
      username_claim: preferred_username
      userdata_params:
        state: state
      scope:
        - openid
        - profile
        - email
        - offline_access
      allow_all: true
      admin_users:
        - admin
      # auto_login: true
      enable_auth_state: true
    JupyterHub:
      authenticator_class: "generic-oauth"
      allow_named_servers: true
      default_url: "/hub/home"

singleuser:
  image:
    name: quay.io/jupyterhub/k8s-singleuser-sample
    tag: 4.1.0
  profileList:
    - display_name: "JupyterLab-4.1.0"
      description: "기본 이미지"
      default: true
    - display_name: "JupyterLab-4.0.0"
      description: "첫 번째 이미지"
      kubespawner_override:
        image: quay.io/jupyterhub/k8s-singleuser-sample:4.0.0
    - display_name: "JupyterLab-3.3.8"
      description: "두 번째 이미지"
      kubespawner_override:
        image: quay.io/jupyterhub/k8s-singleuser-sample:3.3.8
    - display_name: "JupyterLab-3.3.7"
      description: "세 번째 이미지"
      kubespawner_override:
        image: quay.io/jupyterhub/k8s-singleuser-sample:3.3.7

proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30002
  https:
    enabled: false